### PR TITLE
Feature/pvcloudplt 210

### PR DESCRIPTION
**Pull request by mmomont**
- added `domain_endpoint_options` block
- added .gitignore
- added pre-commit hooks
- doc formatting

### CODE REVIEW

**Comment by miroadamy** [comment]
Testing

**Comment by miroadamy** [comment]
Two problems with provided example (examples/vpc):

1) hardcoded subnet, cannot be run in a new account

```
module.aws_es.aws_elasticsearch_domain.es_domain: Still creating... [10s elapsed]

Error: Error creating ElasticSearch domain: ValidationException: The subnet ID 'subnet-02f7242d' does not exist

  on ../../main.tf line 1, in resource "aws_elasticsearch_domain" "es_domain":
   1: resource "aws_elasticsearch_domain" "es_domain" {
```

2) if executed in account where previously run, errors with:

```
module.aws_es.aws_cloudwatch_log_group.es_cloudwatch_log_group: Creating...
module.aws_es.aws_iam_service_linked_role.es[0]: Creating...
module.aws_es.aws_cloudwatch_log_resource_policy.es_aws_cloudwatch_log_resource_policy: Creating...
module.aws_es.aws_cloudwatch_log_resource_policy.es_aws_cloudwatch_log_resource_policy: Creation complete after 1s [id=elasticsearch-vpc-policy]
module.aws_es.aws_cloudwatch_log_group.es_cloudwatch_log_group: Creation complete after 2s [id=elasticsearch-vpc-log_group]

Error: Error creating service-linked role with name es.amazonaws.com: InvalidInput: Service role name AWSServiceRoleForAmazonElasticsearchService has been taken in this account, please try a different suffix.
	status code: 400, request id: 004c1337-584d-4017-a2ca-387d7dbd0395

  on ../../iam.tf line 31, in resource "aws_iam_service_linked_role" "es":
  31: resource "aws_iam_service_linked_role" "es" {


```

**Comment by miroadamy** [comment]
because of the #2 I cannot try to run it in the devops account

IMHO, the script should either 
a) look for existing service role name and try to create one only if not provided
b) use name with suffix so that if the name exists, it does not fail

@dave-anand - opinions ?

**Review by miroadamy — CHANGES_REQUESTED** [review]
Please see my comments above. Thanks

**Review by dave-anand — APPROVED** [review]

**Comment by mmomont** [comment]
@miroadamy looking at the examples I can't say they are easy to run out of the box and I haven't really touched them.

However as you've noticed they need minor changes so it would be easy to run them out of the box without the need to change stuff. That's how majority of our examples work.

**Comment by miroadamy** [comment]
Lets merge this one and continue with the improvements of examples / addressing conflicts in different PR

**Review by miroadamy — COMMENTED** [review]
I pressed the wrong button

**Pull request merged**
